/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACE_AIRPORT_COMMON_H_RPCGEN
#define _PLACE_AIRPORT_COMMON_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include "prog_limits.h"

struct location {
	double latitude;
	double longitude;
};
typedef struct location location;

struct place {
	char *name;
	char *state;
	location loc;
};
typedef struct place place;

struct airport {
	location loc;
	double dist;
	char *code;
	char *name;
	char *state;
};
typedef struct airport airport;

typedef airport airports[NRESULTS];

struct name_state {
	char *name;
	char *state;
};
typedef struct name_state name_state;

struct places_req {
	int req_type;
	union {
		name_state named;
		location loc;
	} places_req_u;
};
typedef struct places_req places_req;

struct place_airports {
	place request;
	airports results;
};
typedef struct place_airports place_airports;

struct places_ret {
	int err;
	union {
		place_airports results;
		char *err_msg;
	} places_ret_u;
};
typedef struct places_ret places_ret;

struct airports_ret {
	int err;
	union {
		airports results;
		char *error_msg;
	} airports_ret_u;
};
typedef struct airports_ret airports_ret;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_location (XDR *, location*);
extern  bool_t xdr_place (XDR *, place*);
extern  bool_t xdr_airport (XDR *, airport*);
extern  bool_t xdr_airports (XDR *, airports);
extern  bool_t xdr_name_state (XDR *, name_state*);
extern  bool_t xdr_places_req (XDR *, places_req*);
extern  bool_t xdr_place_airports (XDR *, place_airports*);
extern  bool_t xdr_places_ret (XDR *, places_ret*);
extern  bool_t xdr_airports_ret (XDR *, airports_ret*);

#else /* K&R C */
extern bool_t xdr_location ();
extern bool_t xdr_place ();
extern bool_t xdr_airport ();
extern bool_t xdr_airports ();
extern bool_t xdr_name_state ();
extern bool_t xdr_places_req ();
extern bool_t xdr_place_airports ();
extern bool_t xdr_places_ret ();
extern bool_t xdr_airports_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACE_AIRPORT_COMMON_H_RPCGEN */
