/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>
#include "place_airport_common.h"

#ifdef __cplusplus
extern "C" {
#endif


#define PLACES_PROG 0x27699175
#define PLACES_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define PLACES_QRY 1
extern  places_ret * places_qry_1(places_req *, CLIENT *);
extern  places_ret * places_qry_1_svc(places_req *, struct svc_req *);
extern int places_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PLACES_QRY 1
extern  places_ret * places_qry_1();
extern  places_ret * places_qry_1_svc();
extern int places_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
